// Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license.

using System.Globalization;
using System.Resources;

namespace RaphaëlBardini.WinClean.Resources
{
    /// <summary>Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.</summary>
    /// <remarks>Replacing the code generated by the ResX engine, to support string formatting in resource properties.</remarks>
    internal class FormattableStrings
    {
        #region Private Fields

        private static readonly CultureInfo s_dataCulture = CultureInfo.CurrentCulture;
        private static readonly ResourceManager s_resourceManager = new(typeof(FormattableStrings).ToString(), typeof(FormattableStrings).Assembly);
        private static readonly CultureInfo s_uiCulture = CultureInfo.CurrentUICulture;

        #endregion Private Fields

        #region Internal Properties

        /// <summary>Gets a formattable localized string.</summary>
        /// <returns>The localized string corresponding to "About programName".</returns>
        internal static string About(string programName)
            => string.Format(s_dataCulture, s_resourceManager.GetString("About", s_uiCulture), programName);

        /// <summary>Gets a formattable localized string.</summary>
        /// <returns>The localized string corresponding to "Version versionNumber".</returns>
        internal static string Version(string version)
            => string.Format(s_dataCulture, s_resourceManager.GetString("Version", s_uiCulture), version);

        #endregion Internal Properties
    }
}
