//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaphaëlBardini.WinClean.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaphaëlBardini.WinClean.Resources.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add script button clicked..
        /// </summary>
        internal static string AddScriptClicked {
            get {
                return ResourceManager.GetString("AddScriptClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canceled button clicked. Prompting user for confirmation....
        /// </summary>
        internal static string CancelClickedPromptingUserConfirmation {
            get {
                return ResourceManager.GetString("CancelClickedPromptingUserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating restore point....
        /// </summary>
        internal static string CreatingRestorePoint {
            get {
                return ResourceManager.GetString("CreatingRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensuring single instance....
        /// </summary>
        internal static string EnsuringSingleInstance {
            get {
                return ResourceManager.GetString("EnsuringSingleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensuring startup path correct....
        /// </summary>
        internal static string EnsuringStartupPathCorrect {
            get {
                return ResourceManager.GetString("EnsuringStartupPathCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing scripts without UI....
        /// </summary>
        internal static string ExecuteNoUI {
            get {
                return ResourceManager.GetString("ExecuteNoUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute scripts button clicked..
        /// </summary>
        internal static string ExecuteScriptsClicked {
            get {
                return ResourceManager.GetString("ExecuteScriptsClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing scripts with UI....
        /// </summary>
        internal static string ExecuteUI {
            get {
                return ResourceManager.GetString("ExecuteUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting the application....
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading MainForm....
        /// </summary>
        internal static string LoadingMainForm {
            get {
                return ResourceManager.GetString("LoadingMainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MainForm loaded..
        /// </summary>
        internal static string MainFormLoaded {
            get {
                return ResourceManager.GetString("MainFormLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebooting for application maintenance....
        /// </summary>
        internal static string RebootingForAppMaintenance {
            get {
                return ResourceManager.GetString("RebootingForAppMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore point created successfully..
        /// </summary>
        internal static string RestorePointCreated {
            get {
                return ResourceManager.GetString("RestorePointCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during restore point creation : {0}
        ///Prompting user to take action..
        /// </summary>
        internal static string RestorePointCreationError {
            get {
                return ResourceManager.GetString("RestorePointCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script execution canceled..
        /// </summary>
        internal static string ScriptExecutionCanceled {
            get {
                return ResourceManager.GetString("ScriptExecutionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Script(s) executed successfully..
        /// </summary>
        internal static string ScriptsExecutedSuccessfully {
            get {
                return ResourceManager.GetString("ScriptsExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Showing completed page....
        /// </summary>
        internal static string ShowingCompletedPage {
            get {
                return ResourceManager.GetString("ShowingCompletedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Showing progress page....
        /// </summary>
        internal static string ShowingProgressPage {
            get {
                return ResourceManager.GetString("ShowingProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Showing warning page....
        /// </summary>
        internal static string ShowingWarningPage {
            get {
                return ResourceManager.GetString("ShowingWarningPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Single instance OK..
        /// </summary>
        internal static string SingleInstanceOk {
            get {
                return ResourceManager.GetString("SingleInstanceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting the application....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting the execution of {0} script(s)....
        /// </summary>
        internal static string StartingExecutionOfScripts {
            get {
                return ResourceManager.GetString("StartingExecutionOfScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup path OK..
        /// </summary>
        internal static string StartupPathOk {
            get {
                return ResourceManager.GetString("StartupPathOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User chose to abort the script execution..
        /// </summary>
        internal static string UserChoseAbortScriptExecution {
            get {
                return ResourceManager.GetString("UserChoseAbortScriptExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User chose to continue script execution anyway..
        /// </summary>
        internal static string UserChoseContinueScriptExecution {
            get {
                return ResourceManager.GetString("UserChoseContinueScriptExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User chose to retry creating a restore point..
        /// </summary>
        internal static string UserChoseRetryCreatingRestorePoint {
            get {
                return ResourceManager.GetString("UserChoseRetryCreatingRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User confirmed cancelation. Canceling script execution....
        /// </summary>
        internal static string UserConfirmedCancelationCanceling {
            get {
                return ResourceManager.GetString("UserConfirmedCancelationCanceling", resourceCulture);
            }
        }
    }
}
